### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by sam0x17** [ptr727/PlexCleaner#115]
I have been getting this error consistently. It does not seem to be tied to a particular file, but happens when I am about 15% through running process on a large folder of nested movies and tv shows. 

* Windows 10
* PlexCleaner 2.8.13
* not running in parallel mode (also happens in parallel mode though)

error:
```
10:52:22 [ERR] <1> "ProcessFilesDriver"
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PlexCleaner.SidecarFile.ReadJson() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/SidecarFile.cs:line 487
   at PlexCleaner.SidecarFile.Read(Boolean& current, Boolean verify) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/SidecarFile.cs:line 128
   at PlexCleaner.SidecarFile.Open(Boolean modified) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/SidecarFile.cs:line 232
   at PlexCleaner.ProcessFile.Refresh(Boolean modified) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/ProcessFile.cs:line 1399
   at PlexCleaner.Process.ProcessFile(String fileName, Boolean& modified, States& state, String& processName) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 470
   at PlexCleaner.Process.<>c__DisplayClass5_0.<ProcessFiles>b__0(String fileName) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 220
   at PlexCleaner.Process.<>c__DisplayClass16_0.<ProcessFilesDriver>b__1(IGrouping`2 keyPair) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 727
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.RunTaskSynchronously(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.PartitionerQueryOperator`1.PartitionerQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at PlexCleaner.Process.ProcessFilesDriver(List`1 fileList, String taskName, Func`2 taskFunc) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Process.cs:line 714
10:52:22 [INF] <1> Completed "Process"
10:52:22 [INF] <1> Processing time : 00:00:01.9141056
10:52:22 [INF] <1> Total files : 11513
10:52:22 [INF] <1> Error files : 0
10:52:22 [INF] <1> Modified files : 0
10:52:22 [INF] <1> VerifyFailed files : 0
10:52:22 [INF] <1> Deleting empty folders ...
10:52:22 [INF] <1> Looking for empty folders in "D:\\Plex"
10:52:22 [INF] <1> Deleted folders : 0
```

**Comment by ptr727** [comment]
Could you please zip and attach the complete log, or at minimum show a couple lines before the crash, where it logs what file it is processing.
Could you look at the log, and determine what file is being processed, looks like a sidecar file, and provide a copy of that sidecar please.

**Comment by sam0x17** [comment]
Aha, it seems to have been caused by an empty (0 byte) sidecar file. Deleting the file resolved the issue, so I'm guessing maybe at some point the script might have been killed before the sidecar file was able to be written. Would be cool if your code could use atomic writes for sidecar file changes or handle the case where it attempts to read an empty or invalid sidecar file by resetting the file.

**Comment by ptr727** [comment]
I will add a test for sidecar validity.
