### ISSUE TITLE
ffmpeg cannot download

### ISSUE THREAD

**Issue by baetz** [ptr727/PlexCleaner#214]
### Is this a new issue that can be reproduced?

- [X] This is a new issue that can be reproduced.

### Which operating systems reproduce the issue?

- [X] Windows
- [ ] Docker
- [ ] Other

### Version information.

OS Version:  Windows 11 Pro 22H2.

### Steps to reproduce?

Run as Admin PlexCleaner checkfornewtools --settingsfile PlexCleaner.json

### Commandline.

```Text
Run as Admin >PlexCleaner defaultsettings --settingsfile PlexCleaner.json
Run as Admin >PlexCleaner checkfornewtools --settingsfile PlexCleaner.json
```

### Relevant log output.

```Text
Microsoft Windows [Version 10.0.22621.2134]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Windows\System32>cd C:\ProgramData\Plex-Cleaner

C:\ProgramData\Plex-Cleaner>PlexCleaner defaultsettings --settingsfile PlexCleaner.json
Press Ctrl+C or Ctrl+Z or Ctrl+Q to exit.
18:07:00 [INF] <1> Writing default settings to "PlexCleaner.json"
18:07:01 [INF] <1> Exit Code : 0

C:\ProgramData\Plex-Cleaner>PlexCleaner checkfornewtools --settingsfile PlexCleaner.json
Press Ctrl+C or Ctrl+Z or Ctrl+Q to exit.
18:08:26 [INF] <1> Loading settings from : "PlexCleaner.json"
18:08:26 [INF] <1> Application Version : "PlexCleaner : 3.2.34+6ae7f3b79e.6ae7f3b79e661af89be88371bd931ef2409cc632 (Release)"
18:08:26 [INF] <1> Runtime Version : ".NET 7.0.10" : "win10-x64"
18:08:26 [INF] <1> OS Version : "Microsoft Windows 10.0.22621"
18:08:26 [INF] <1> Build Date : 07/21/2023 17:25:52
18:08:26 [INF] <1> Parallel Processing: False : Thread Count: 1, Processor Count: 24
18:08:26 [WRN] <1> Downloading missing SevenZip ... : ""C:\\ProgramData\\Plex-Cleaner\\Tools\\SevenZip\\x64\\7za.exe""
18:08:26 [WRN] <1> Creating missing Tools folder : ""C:\\ProgramData\\Plex-Cleaner\\Tools\\""
18:08:26 [INF] <1> Downloading "7zr.exe" ...
18:08:27 [INF] <1> SevenZip : Reading latest version from : "https://www.7-zip.org/download.html"
18:08:27 [INF] <1> Downloading ""7z2301-extra.7z"" ...
18:08:28 [INF] <1> Extracting "C:\\ProgramData\\Plex-Cleaner\\Tools\\7z2301-extra.7z" ...

7-Zip (r) 23.01 (x86) : Igor Pavlov : Public domain : 2023-06-20

Scanning the drive for archives:
1 file, 1027828 bytes (1004 KiB)

Extracting archive: C:\ProgramData\Plex-Cleaner\Tools\7z2301-extra.7z
--
Path = C:\ProgramData\Plex-Cleaner\Tools\7z2301-extra.7z
Type = 7z
Physical Size = 1027828
Headers Size = 531
Method = LZMA:22 BCJ2
Solid = +
Blocks = 2

Everything is Ok

Files: 18
Size:       3959775
Compressed: 1027828
18:08:28 [INF] <1> Checking for new tools ...
18:08:28 [INF] <1> FfMpeg : Getting latest version ...
18:08:28 [INF] <1> FfMpeg : Reading latest version from : "https://www.gyan.dev/ffmpeg/builds/release-version"
18:08:29 [INF] <1> FfMpeg : Getting download URI details : "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.0-full_build.7z"
18:08:59 [ERR] <1> "GetContentInfo"
System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at InsaneGenius.Utilities.Download.GetContentInfo(Uri uri, Int64& size, DateTime& modifiedTime)
   at PlexCleaner.Tools.GetUrlDetails(MediaToolInfo mediaToolInfo) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Tools.cs:line 345
   at PlexCleaner.Tools.CheckForNewTools() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Tools.cs:line 273
   at PlexCleaner.Program.CheckForNewToolsCommand(CommandLineOptions options) in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Program.cs:line 275
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.Invoke(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<BuildInvocationChain>b__0(InvocationContext invocationContext, Func`2 _)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<UseParseErrorReporting>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<UseHelp>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<UseVersionOption>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<UseTypoCorrections>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<UseSuggestDirective>b__18_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<UseParseDirective>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<RegisterWithDotnetSuggest>b__5_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<UseEnvironmentVariableDirective>b__6_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<UseExceptionHandler>b__0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_2.<BuildInvocationChain>b__3(InvocationContext c)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__1_0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<CancelOnProcessTermination>b__1_0(InvocationContext context, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_1.<BuildInvocationChain>b__2(InvocationContext ctx, Func`2 next)
   at System.CommandLine.Invocation.InvocationPipeline.<Invoke>g__FullInvocationChain|3_0(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.Invoke(IConsole console)
   at System.CommandLine.CommandExtensions.Invoke(Command command, String[] args, IConsole console)
   at PlexCleaner.CommandLineOptions.Invoke() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/CommandLineOptions.cs:line 30
   at PlexCleaner.Program.Main() in /home/runner/work/PlexCleaner/PlexCleaner/PlexCleaner/Program.cs:line 64
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at InsaneGenius.Utilities.Download.GetContentInfo(Uri uri, Int64& size, DateTime& modifiedTime)
18:08:59 [ERR] <1> FfMpeg : Failed to get download URI details : "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.0-full_build.7z"
18:08:59 [INF] <1> Exit Code : 1

C:\ProgramData\Plex-Cleaner>
```

### Settings file.

Default settings

**Comment by ptr727** [comment]
This is the error: `18:08:59 [ERR] <1> FfMpeg : Failed to get download URI details : "https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-6.0-full_build.7z"`, most likely the site was not available from your network.

**Comment by baetz** [comment]
from my browser i can download it with no problems

**Comment by ptr727** [comment]
Ok, try not running as admin, why do you need to run as admin, remember when you run as admin you are running in a different user session, so not the same permissions, or settings, or windows profile as when you run from edge/chrome/ff etc.?

**Comment by ptr727** [comment]
You can disable the checkfornewtools option in settings, and you can manually add the required tools, I am busy and can't check the folders now. I see you run Win10, I'm not doing any testing with Win10, just docker and Win11.

**Comment by ptr727** [comment]
Needs to look something like this:

```


    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\FfMpeg
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\FfMpeg\bin
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\FfMpeg\doc
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\FfMpeg\presets
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\HandBrake
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\HandBrake\doc
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MediaInfo
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MediaInfo\Plugin
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MediaInfo\Plugin\Custom
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\data
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\data\sounds
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\bg
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\ca
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\de
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\en
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\es
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\fr
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\it
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\ja
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\ko
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\licenses
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\nl
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\pl
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\ru
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\uk
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\zh_CN
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\doc\zh_TW
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\examples
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\bg
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\bg\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ca
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ca\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\cs
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\cs\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\de
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\de\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\es
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\es\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\eu
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\eu\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\fr
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\fr\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\it
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\it\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ja
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ja\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ko
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ko\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\libqt
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\lt
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\lt\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\nl
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\nl\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\pl
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\pl\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\pt
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\pt\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\pt_BR
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\pt_BR\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ro
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ro\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ru
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\ru\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\sr_RS
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\sr_RS\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\sr_RS@latin
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\sr_RS@latin\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\sv
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\sv\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\tr
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\tr\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\uk
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\uk\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\zh_CN
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\zh_CN\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\zh_SG
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\zh_SG\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\zh_TW
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\locale\zh_TW\LC_MESSAGES
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\MkvToolNix\tools
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\SevenZip
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\SevenZip\Far
    Directory: C:\Users\piete\source\repos\ptr727\PlexCleaner\PlexCleaner\bin\Debug\net7.0\Tools\SevenZip\x64
```

**Comment by ptr727** [comment]
Closing due to no activity.

**Comment by C0nw0nk** [comment]
@ptr727 

I also found this issue.

My soloution was to avoid allowing FFMPEG from plexcleaner to download from gyan.dev 

Use GITHUB only the gyan dev site times out occasionally.

https://github.com/GyanD/codexffmpeg/releases/download/6.0/ffmpeg-6.0-full_build.7z

Also @ptr727  You can use GITHUBs API inside your code to grab the latest ffmpeg package like this.

https://api.github.com/repos/GyanD/codexffmpeg/releases/latest

*full_build.7z is the package we use.

**Comment by ptr727** [comment]
Ok, I'll keep it in mind for a future change. GitHub was not mentioned anywhere as a mirror for gyan.dev when this logic was implemented (the previous windows download site shut down), I'll need to make sure the tag logic matches the releases file content logic gyan.dev uses.

**Comment by C0nw0nk** [comment]
Just curious @ptr727 The other dependancies in tools for example handbrake

They are also maintained via github.

https://github.com/HandBrake/HandBrake/releases

It might be a good idea to use their official github over third party sites / their own websites due to the uptime and server configuration issues that is causing us issues.

**Comment by ptr727** [comment]
https://github.com/ptr727/PlexCleaner/blob/main/PlexCleaner/HandBrakeTool.cs#L74
