### ISSUE TITLE
Crash on no audio stream

### ISSUE THREAD

**Issue by Migushthe2nd** [ptr727/PlexCleaner#81]
Some of my video files don't have an audio channel. This causes PlexCleaner to crash. I've noticed this with the MJPEG codec (AVI, wmv). Not sure about other codecs.

The `First()` call throws an error:
https://github.com/ptr727/PlexCleaner/blob/eb592ee4f892d50cb3b0ceb7a17588bd459590c0/PlexCleaner/ProcessFile.cs#L1013-L1016

```cmd
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PlexCleaner.ProcessFile.GetBitrateInfo(BitrateInfo& bitrateInfo) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\ProcessFile.cs:line 1013
   at PlexCleaner.ProcessFile.VerifyBitrate() in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\ProcessFile.cs:line 623
   at PlexCleaner.ProcessFile.Verify(Boolean conditional, Boolean& modified) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\ProcessFile.cs:line 542
   at PlexCleaner.Process.ProcessFile(FileInfo fileinfo, Boolean& modified, States& state, FileInfo& processInfo) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\Process.cs:line 268
   at PlexCleaner.Process.<>c__DisplayClass3_0.<ProcessFiles>b__0(FileInfo fileInfo) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\Process.cs:line 114
   at PlexCleaner.Process.ProcessFilesDriver(List`1 fileList, String taskName, Func`2 taskFunc) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\Process.cs:line 542
   at PlexCleaner.Process.ProcessFiles(List`1 fileList) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\Process.cs:line 111
   at PlexCleaner.Program.ProcessCommand(CommandLineOptions options) in D:\a\PlexCleaner\PlexCleaner\PlexCleaner\Program.cs:line 109
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass15_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass26_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass24_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__23_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__8_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__7_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass11_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by ptr727** [comment]
There is a test for audio and video track counts before calling the bitrate calculation:
https://github.com/ptr727/PlexCleaner/blob/eb592ee4f892d50cb3b0ceb7a17588bd459590c0/PlexCleaner/ProcessFile.cs#L477-L485

I wonder if there is a difference in track counts between what ffprobe and mediainfo reports.
Could you possibly share a sample file that exhibits the problem?

**Comment by Migushthe2nd** [comment]
Hmm this actually happens with files that do have an audio track as well. These are family videos so I'd rather not share these here publicly. What is your telegram handle?

**Comment by Migushthe2nd** [comment]
<img width="274" alt="image" src="https://user-images.githubusercontent.com/22274715/148652937-102b4de0-bf23-4241-bebe-2d0701ac6f6e.png">
Is this of use?

**Comment by ptr727** [comment]
I can see form the log what happens, the file is remuxed from WMV to MKV, and in the process the video track is removed.

I do have a WMV sample, but it does not exhibit this problem.
Could you possibly create a test file using the same format, just a few seconds will do, and I'll try to get it to convert to MKV H265 AC3 without the errors?

**Comment by Migushthe2nd** [comment]
I can send the file from above via telegram if that is okay with you?

**Comment by Migushthe2nd** [comment]
Here's a small test file https://tmpfiles.org/185781/outfile.wmv

**Comment by ptr727** [comment]
Thx, let me try it, else we can telegram share (wondering how to exchange contact info with github removing dm feature?)

**Comment by ptr727** [comment]
Ah shoot;
```
// Media file must be at least 2 * the hash window length
Debug.Assert(MediaFileInfo.Length >= 2 * HashWindowLength);
```

Could you make it longer than 128KB, or telegram, how do we share contact info?

**Comment by Migushthe2nd** [comment]
Does this suffice? https://tmpfiles.org/185785/outfile.wmv

**Comment by ptr727** [comment]
Unfortunately that file does not have the mjpeg cover art track.
Let's try telegram, how do we exchange contact info without the world seeing it here?

**Comment by Migushthe2nd** [comment]
Oh I think my username will work. Try searching for `@migush`

**Comment by ptr727** [comment]
Should be fixed now, please let me know.
Remember to add the codec types to the JSON config if you want the wma2 audio and wmv3 video to be converted to ac3 and h265.

**Comment by Migushthe2nd** [comment]
It's working! I have a few more files with weird audio channels that have issues. I'll send one via telegram

**Comment by ptr727** [comment]
I can't get the AVI you sent to convert to H265 and AC3, the MJPEG video converts, but the PCM audio is not recognized after converting to AC3 or AAC.

Do try the develop branch I just pushed, you can build locally, or I do publish a develop docker build. Also add the codecs you want to reencode to the JSON config file if not already added.

I may not get it working 100% with AVI and all the many funky codecs.

**Comment by ptr727** [comment]
Merged to main branch.
